Tweaking PHP detect
This is for scenarios where the server is running PHP 5 and 7 in parallel.

diff --git a/bin/laravel-site b/bin/laravel-site
--- a/bin/laravel-site
+++ b/bin/laravel-site
@@ -41,16 +41,13 @@ if [ -e "/etc/nginx" ]; then
 fi
 
 # determine the verion of PHP available
-config="null"
 if [ -e "/var/run/php/php7.0-fpm.sock" ]; then
-   config="laravel-php7.conf"
-fi
-if [ -e "/var/run/php5-fpm.sock" ]; then
-   config="laravel-php5.conf"
-fi
-if [ $config = "null" ]; then
-	echo "Unable to determine version of PHP. Script cannot proceed."
-	exit 1;
+    config="laravel-php7.conf"
+elif [ -e "/var/run/php5-fpm.sock" ]; then
+    config="laravel-php5.conf"
+else
+    echo "Unable to determine version of PHP. Script cannot proceed."
+    exit 1;
 fi
 
 # Create site folders
