Updating to support Apache web server

diff --git a/bin/wp-site b/bin/wp-site
--- a/bin/wp-site
+++ b/bin/wp-site
@@ -4,7 +4,7 @@
 # WordPress Site Setup Script - Ubuntu 14.04
 #
 # DESCRIPTION
-# Helper script that sets up necessary folders and Nginx server configurations
+# Helper script that sets up necessary folders and web server configurations
 # for DEV, Stage, and UAT versions of a WordPress-based site.
 #
 # PARAMETERS
@@ -16,44 +16,72 @@
 # - Reloads the Nginx configuration
 #
 # ASSUMPTIONS
-# - Web server is Nginx
-# - Web server user is "www-data"
-# - PHP FPM is located in its "normal" place
+# - Web server is Apache or Nginx.
+# - Web server user is "www-data".
+# - For servers running Nginx, PHP FPM is located in its "normal" place.
 #
 #===================================================================================
 
 # One parameter is required
 if [ $# != 1 ]; then
    echo "Usage: wp-site [url]";
-   exit 1
+   exit 1;
 fi
 
 # web server user
 user="www-data"
 
-# determine the verion of PHP available
-config="null"
-if [ -e "/var/run/php/php7.0-fpm.sock" ]; then
-   config="wordpress-php7.conf"
-fi
-if [ -e "/var/run/php5-fpm.sock" ]; then
-   config="wordpress-php5.conf"
-fi
-if [ $config = "null" ]; then
-	echo "Unable to determine version of PHP. Script cannot proceed."
-	exit 1;
+# determine the environment
+if [ -e "/etc/apache2" ]; then
+    websrv="Apache";
+else
+    websrv="Nginx";
+    config="null"
+    if [ -e "/var/run/php/php7.0-fpm.sock" ]; then
+       config="wordpress-php7.conf"
+    fi
+    if [ -e "/var/run/php5-fpm.sock" ]; then
+       config="wordpress-php5.conf"
+    fi
+    if [ $config = "null" ]; then
+        echo "Unable to determine version of PHP. Script cannot proceed."
+        exit 1;
+    fi
 fi
 
-# Create site folders
-mkdir -p /usr/share/nginx/html/dev/$1
-mkdir -p /usr/share/nginx/html/stage/$1
-mkdir -p /usr/share/nginx/html/uat/$1
-mkdir -p /usr/share/nginx/html/prod/$1
+# configure for Apache
+if [ $websrv = "Apache" ]; then
 
-# Create Nginx server configs
-cp ~/utils/nginx/$config /etc/nginx/sites-available/$1.conf
-sudo sed -i "s/SITEURL/$1/g" /etc/nginx/sites-available/$1.conf
-ln -s /etc/nginx/sites-available/$1.conf /etc/nginx/sites-enabled/$1.conf
+    # create folders
+    mkdir -p /var/www/dev/$1
+    mkdir -p /var/www/stage/$1
+    mkdir -p /var/www/uat/$1
+    mkdir -p /var/www/prod/$1
 
-# Reload Nginx configuration
-sudo service nginx reload
+    # create web server configs
+    cp ~/utils/apache/$config /etc/apache2/sites-available/$1.conf
+    sudo sed -i "s/SITEURL/$1/g" /etc/apache2/sites-available/$1.conf
+    ln -s /etc/apache2/sites-available/$1.conf /etc/apache2/sites-enabled/$1.conf
+
+    # reload web server config
+    sudo /etc/init.d/apache2 graceful
+fi
+
+
+# configure for Nginx
+if [ $websrv = "Nginx" ]; then
+
+    # create folders
+    mkdir -p /usr/share/nginx/html/dev/$1
+    mkdir -p /usr/share/nginx/html/stage/$1
+    mkdir -p /usr/share/nginx/html/uat/$1
+    mkdir -p /usr/share/nginx/html/prod/$1
+
+    # create web server configs
+    cp ~/utils/nginx/$config /etc/nginx/sites-available/$1.conf
+    sudo sed -i "s/SITEURL/$1/g" /etc/nginx/sites-available/$1.conf
+    ln -s /etc/nginx/sites-available/$1.conf /etc/nginx/sites-enabled/$1.conf
+
+    # reload web server config
+    sudo service nginx reload
+fi
